In [28]:
## import necessary libraries
import pandas as pd

In [29]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/FilteredData/2025.csv')

In [30]:
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3.0,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,000123c8701799c3f1c69fc5b9237441afcf6161
3,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,000236c508a3b3fd90b47464c6790ebd2ced3228
4,2025-10-09 14:24:47,Targeted,TEXAS,NaN,El Paso Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,2025-07-12 00:00:00,"EPC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - El Paso, TX SPC Sub-Office",1 Convicted Criminal,3.0,0002a26f2085a370bf4be4fec089a1124f2f4e03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113056,2025-12-31 16:42:51,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",-,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
113057,2025-12-31 22:42:46,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",---,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
113058,2025-12-31 20:00:25,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,NaN
113059,2025-12-15 12:54:00,Collateral,CALIFORNIA,NaN,NaN,Law Enforcement Area Response Units,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"LNBGENERAL AREA, NON-SPECIFIC",NaN,HSI SAC LOS ANGELES,NaN,NaN,NaN
113060,2025-12-11 03:55:00,Targeted,TEXAS,NaN,Dallas Area of Responsibility,287g Task Force,ICE,287(g) Program,2 Pending Criminal Charges,NaN,...,MEXICO,Male,NaN,NaN,PANOLA COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN

In [31]:
df2 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/FilteredData/2025pt2.csv')

In [32]:
df2

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3.0,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,000123c8701799c3f1c69fc5b9237441afcf6161
3,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,000236c508a3b3fd90b47464c6790ebd2ced3228
4,2025-10-09 14:24:47,Targeted,TEXAS,NaN,El Paso Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,2025-07-12 00:00:00,"EPC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - El Paso, TX SPC Sub-Office",1 Convicted Criminal,3.0,0002a26f2085a370bf4be4fec089a1124f2f4e03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113056,2025-12-31 16:42:51,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",-,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
113057,2025-12-31 22:42:46,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",---,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
113058,2025-12-31 20:00:25,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,NaN
113059,2025-12-15 12:54:00,Collateral,CALIFORNIA,NaN,NaN,Law Enforcement Area Response Units,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"LNBGENERAL AREA, NON-SPECIFIC",NaN,HSI SAC LOS ANGELES,NaN,NaN,NaN
113060,2025-12-11 03:55:00,Targeted,TEXAS,NaN,Dallas Area of Responsibility,287g Task Force,ICE,287(g) Program,2 Pending Criminal Charges,NaN,...,MEXICO,Male,NaN,NaN,PANOLA COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN

In [33]:
df25 = pd.concat([df1, df2])

In [34]:
df25.to_csv('FilteredData/2025AllArrests.csv', index = True)

In [35]:
df25_state = df25["State"].value_counts()

In [36]:
df25_state

TEXAS                          61550
CALIFORNIA                     20952
FLORIDA                        20804
NEW YORK                        8154
ARIZONA                         6864
GEORGIA                         6836
TENNESSEE                       6666
ILLINOIS                        6574
NEW JERSEY                      6530
VIRGINIA                        5800
PENNSYLVANIA                    5160
OKLAHOMA                        3930
NORTH CAROLINA                  3822
ALABAMA                         3762
NEW MEXICO                      3624
MARYLAND                        3536
LOUISIANA                       3400
OHIO                            3142
MASSACHUSETTS                   2798
WASHINGTON                      2752
UTAH                            2650
SOUTH CAROLINA                  2584
OREGON                          2504
MINNESOTA                       2484
INDIANA                         2438
COLORADO                        2392
MICHIGAN                        2262
ARKANSAS                        1870
MISSOURI                        1716
KENTUCKY                        1562
MISSISSIPPI                     1540
NEVADA                          1464
DISTRICT OF COLUMBIA            1396
WEST VIRGINIA                   1286
KANSAS                          1220
NEBRASKA                         968
WISCONSIN                        940
IOWA                             930
IDAHO                            808
WYOMING                          788
CONNECTICUT                      502
DELAWARE                         414
RHODE ISLAND                     372
SOUTH DAKOTA                     348
NEW HAMPSHIRE                    276
PUERTO RICO                      268
HAWAII                           208
MAINE                            202
NORTH DAKOTA                     134
MONTANA                          102
ALASKA                            70
NORTHERN MARIANA ISLANDS          64
VIRGIN ISLANDS                    62
ARMED FORCES - THE AMERICAS       48
GUAM                              20
VERMONT                           18
OTHER                              2
ARMED SERVICES - PACIFIC           2
Name: State, dtype: int64

In [37]:
df25_state.to_csv('FilteredData/2025DeportationByState.csv', index=True)

In [38]:
df_NY = df25.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
94,2025-11-11 07:00:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,MEXICO,Male,2025-11-16 00:00:00,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0039dff0156f320292971c05a14bfa6e3946cb32
105,2025-12-17 09:30:47,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Female,2026-01-27 00:00:00,2026-01-06 00:00:00,ERIE COUNTY,NaN,"BUFFALO, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00415c1cb95bdf48f01e661ab7a9f918d36407be
141,2025-11-03 09:00:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-24 00:00:00,2025-12-04 00:00:00,"NBG GENERAL AREA, NON-SPECIFIC",-,"Newburgh NY, Sub-Office",1 Convicted Criminal,2.0,0054d4ce81786b739538665b21b90a7e3a369dac
161,2025-11-17 12:40:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,EL SALVADOR,Male,2026-02-06 00:00:00,2026-01-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",2 Pending Criminal Charges,NaN,005ca75a7a1899aec34184d6f6c85fdf988ac97a
166,2025-12-05 09:59:03,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00611d42a3c81d54bb49e55b9d6e1593de0ddf67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108519,2025-10-21 08:34:15,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN
108861,2025-10-31 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
110248,2025-12-03 10:26:19,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,GUATEMALA,Male,NaN,NaN,"NBG GENERAL AREA, NON-SPECIFIC",NaN,"Newburgh NY, Sub-Office",NaN,NaN,NaN
110347,2025-12-04 17:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
112859,2025-12-28 20:40:32,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,ECUADOR,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [43]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

CIP GENERAL AREA, NON-SPECIFIC             1808
NDD - 26 FEDERAL PLAZA NY, NY              1780
FUGITIVE OPERATIONS NY STATE                966
ERIE COUNTY                                 550
ATD NY STATE                                448
                                           ...
HARTFORD, CT                                  2
LIVINGSTON COUNTY JAIL                        2
CAP - ORANGE COUNTY PROBATION  NY STATE       2
FUG OPS - LOS ANGELES, CA STATE               2
OCP GENERAL AREA, NON-SPECIFIC                2
Name: Apprehension Site Landmark, Length: 94, dtype: int64

In [44]:
NYcounts.to_csv('FilteredData/2025DeportationByNY.csv', index=True)

In [45]:
df_NY['Apprehension Site Landmark'].unique()

array(['FUGITIVE OPERATIONS NY STATE', 'ERIE COUNTY',
       'NBG GENERAL AREA, NON-SPECIFIC', 'CIP GENERAL AREA, NON-SPECIFIC',
       'ALBANY COUNTY', 'ORLEANS COUNTY',
       'CAP - USM - SOUTHERN DISTRICT NY STATE', 'GENESEE COUNTY',
       'MONTGOMERY COUNTY', 'CHAMPLAIN POE',
       'NDD - 26 FEDERAL PLAZA NY, NY', 'FUGITIVE OPERATIONS NY State',
       'SCHENECTADY COUNTY', 'WENDE CORRECTIONAL FACILITY',
       'CAP - BOP BROOKLYN NY STATE', 'ONONDAGA COUNTY', 'ATD NY STATE',
       'SARATOGA COUNTY', 'LEWISTON BRIDGE POE', 'BROOME COUNTY JAIL',
       'HAR GENERAL AREA, NON-SPECIFIC', 'MONROE COUNTY',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'XNY GENERAL AREA, NON-SPECIFIC', 'PEACE BRIDGE POE',
       'ONEIDA COUNTY', 'CAP - EMTC - ERIC M. TAYLOR CENTER NY STATE',
       'WAYNE COUNTY', 'WHP GENERAL AREA, NON-SPECIFIC', 'BROOME COUNTY',
       'CAP - ORANGE COUNTY JAIL NY STATE',
       'CAP - ROCKLAND COUNTY PROBATION  NY STATE', 'MONROE COUNTY JAIL',
       'RENSSELAER COUNTY',
       'CAP - PORT JERVIS CITY POLICE DEPARMENT, NY STATE',
       'CAP - DUTCHESS COUNTY JAIL  NY STATE', 'NIAGARA COUNTY',
       'NON-DETAINED AND JUVENILE', 'OSWEGO COUNTY', 'ESSEX COUNTY',
       'ALLEGANY COUNTY', 'ONEIDA COUNTY JAIL', 'WARREN COUNTY',
       'CLINTON COUNTY', 'MONTGOMERY COUNTY JAIL',
       'CAP - USM - EASTERN DISTRICT NY State', 'COLUMBIA COUNTY',
       'NEWARK PD', 'CAP - PUTNAM COUNTY PROBATION  NY STATE',
       'FISHKILL CORRECTIONAL FACILITY', 'CHAUTAUQUA COUNTY',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'CAP - COUNTY, STATE, LEA REF NY STATE',
       'CAP - ULSTER CORRECTIONAL FACILITY NY STATE',
       'PHI GENERAL AREA, NON-SPECIFIC', 'OTSEGO COUNTY',
       'ONONDAGA COUNTY JAIL', 'GREENE COUNTY',
       'NON-DETAINED and Juvenile', 'HARTFORD, CT',
       'LIVINGSTON COUNTY JAIL', 'At large arrest Nassau County',
       'CAP - ORANGE COUNTY PROBATION  NY STATE',
       'FUG OPS - LOS ANGELES, CA STATE', 'ALBION CORRECTIONAL FACILITY',
       'SYR GENERAL AREA, NON-SPECIFIC', 'CATTARAUGUS COUNTY',
       'NEW GENERAL AREA, NON-SPECIFIC', 'VCAS-FACILITY ARREST NY',
       'WASHINGTON COUNTY', 'FOS GENERAL AREA, NON-SPECIFIC',
       'JCART STREET ARREST NY STATE', 'RAINBOW BRIDGE POE',
       'ICE ERO NEWARK', 'SCHENECTADY COUNTY JAIL',
       'CAP - PUTNAM COUNTY JAIL NY STATE',
       'ECP GENERAL AREA, NON-SPECIFIC', 'At large arrest Suffolk County',
       'STUBEN COUNTY JAIL', 'ALBANY COUNTY JAIL', 'ATLANTA, GA',
       'NIAGARA COUNTY JAIL', 'WYOMING COUNTY JAIL', 'WARREN COUNTY JAIL',
       'RENSSELAER COUNTY JAIL', 'MADISON COUNTY', 'ORLEANS COUNTY JAIL',
       'CAP - SPRING VALLEY POLICE DEPARTMENT, NY STATE',
       'BUFFALO FEDERAL DETENTION FACILITY', 'Nassau County Jail',
       'LIVINGSTON COUNTY', 'TOMPKINS COUNTY',
       'GREEN HAVEN CORRECTIONAL FACILITY',
       'OCP GENERAL AREA, NON-SPECIFIC'], dtype=object)

In [46]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [47]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [48]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
166,2025-12-05 09:59:03,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00611d42a3c81d54bb49e55b9d6e1593de0ddf67
1663,2025-12-04 10:00:36,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,TURKIYE,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,03e9499893f928bc07bc98740fd4dc592340b0a0
2056,2025-12-05 09:25:32,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,04ca8187f4abb078b20818486b96b07abdadc650
2220,2025-10-01 11:43:45,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,E-Charging Document Canceled by ICE,...,MAURITANIA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,05402d60ce58c53d4116e92921070adc60c38895
2527,2025-12-22 11:20:11,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,05f4628b5de2cf37f19f947c1233e2d6daa245c3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105512,2025-12-02 12:13:00,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,CONGO,Male,NaN,2010-11-04 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f9e158ab97d9a2e6c85717cefd26b77a95e7787b
106245,2025-12-18 12:27:18,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,INDIA,Male,NaN,NaN,ALBANY COUNTY,ICE Wall FY26,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fbafaac8f1e93b9f882b488265c9bfa514337919
106376,2025-12-02 08:18:41,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Male,NaN,NaN,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fbf3a0d47ab7ef7707d3b98a455ee77ad347b3e7
106380,2025-11-19 11:59:32,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,ACTIVE,...,EL SALVADOR,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,fbf6197e24defb4cc263b427ffd6b1b790c47491
107775,2025-10-17 09:20:31,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,NICARAGUA,Male,2025-11-13 00:00:00,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,ff72559666884b8a873bd40200cdaf181c05b356

In [49]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            196
ALBANY COUNTY              150
RENSSELAER COUNTY           34
WARREN COUNTY                4
GREENE COUNTY                2
SCHENECTADY COUNTY JAIL      2
WARREN COUNTY JAIL           2
RENSSELAER COUNTY JAIL       2
Name: Apprehension Site Landmark, dtype: int64

In [50]:
df_CR.to_csv('FilteredData/2025CapitalRegionICEArrests.csv', index = True)