In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/RawData/2025_pt1.csv')

In [3]:
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
1,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
4,2025-02-19 00:00:00,NaN,KANSAS,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-04-04 00:00:00,2020-02-07 00:00:00,"WIC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Wichita, KS Sub-Office",2 Pending Criminal Charges,NaN,00019569acea0c5120fc0e55d6254c7d4aad2b22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203816,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
203817,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
203818,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
203819,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
203820,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [4]:
df2 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/RawData/2025_pt2.csv')

In [5]:
df2

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3.0,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,000123c8701799c3f1c69fc5b9237441afcf6161
3,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
4,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1.0,000236c508a3b3fd90b47464c6790ebd2ced3228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191541,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191542,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191543,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191544,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191545,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [6]:
secondterm = pd.concat([df1, df2])

In [7]:
secondterm

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
1,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
4,2025-02-19 00:00:00,NaN,KANSAS,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-04-04 00:00:00,2020-02-07 00:00:00,"WIC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Wichita, KS Sub-Office",2 Pending Criminal Charges,NaN,00019569acea0c5120fc0e55d6254c7d4aad2b22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191541,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191542,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191543,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191544,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191545,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [8]:
secondterm["State"].value_counts()

TEXAS                    94525
FLORIDA                  37027
CALIFORNIA               33557
NEW YORK                 13895
GEORGIA                  13743
                         ...
ARMED FORCES - EUROPE        2
OTHER                        2
MEXICO                       1
TAMAULIPAS                   1
CHIAPAS                      1
Name: State, Length: 63, dtype: int64

In [9]:
statecount = secondterm["State"].value_counts()

In [11]:
statecount.to_csv('RawData/DeportationByState.csv', index=True)

In [21]:
df_NY = secondterm.query('State == "NEW YORK"')

In [22]:
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
14,2025-09-16 08:33:41,Collateral,NEW YORK,NaN,Boston Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-12-22 00:00:00,2025-12-04 00:00:00,FUGITIVE OPERATIONS MA,Boston,"BOSTON, MA, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,0003d477c82b5f0795916635f4da101d37d6924c
39,2025-01-28 12:26:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,SENEGAL,Male,2025-04-10 00:00:00,2023-03-03 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000c16c2e97d9a2d6a84ec0954b1fd204ee96634
48,2025-07-25 11:29:25,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-10-23 00:00:00,2025-09-26 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000e1b3e91ccc931e58311ebe59363dfb727adc9
66,2025-06-09 13:03:41,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0014a87083eb6ebdd1e1d6563016150e7aa8ae50
89,2025-09-12 14:29:15,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2025-12-02 00:00:00,2019-10-28 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3.0,001c20aa9fa402e9dfe2fe2552a49ce677540953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184814,2025-10-21 08:34:15,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN
185156,2025-10-31 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
186543,2025-12-03 10:26:19,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,GUATEMALA,Male,NaN,NaN,"NBG GENERAL AREA, NON-SPECIFIC",NaN,"Newburgh NY, Sub-Office",NaN,NaN,NaN
186642,2025-12-04 17:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN
189191,2025-12-28 20:40:32,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,ECUADOR,Male,NaN,NaN,FUGITIVE OPERATIONS NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [44]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()

In [45]:
NYcounts.to_csv('RawData/DeportationByNY.csv', index=True)

In [29]:
df_NY['Apprehension Site Landmark'].unique()

array(['FUGITIVE OPERATIONS MA', 'NDD - 26 FEDERAL PLAZA NY, NY',
       'CIP GENERAL AREA, NON-SPECIFIC', 'ATD NY STATE', 'ALBANY COUNTY',
       'RENSSELAER COUNTY', 'ERIE COUNTY',
       'WHP GENERAL AREA, NON-SPECIFIC', 'ONONDAGA COUNTY',
       'SCHENECTADY COUNTY', 'FUGITIVE OPERATIONS NY STATE',
       'NBG GENERAL AREA, NON-SPECIFIC', 'NON-DETAINED and Juvenile',
       'CLINTON COUNTY', 'CAP - BOP BROOKLYN NY STATE',
       'FOS GENERAL AREA, NON-SPECIFIC', 'MONROE COUNTY',
       'SARATOGA COUNTY', 'JCART STREET ARREST NY STATE',
       'OSWEGO COUNTY JAIL', 'CHAUTAUQUA COUNTY',
       'MIDSTATE CORRECTIONAL FACILITY',
       'CAP - QUEENSBORO CORRECTIONAL FACILITY NY STATE',
       'CATTARAUGUS COUNTY', 'CAP - USM - SOUTHERN DISTRICT NY STATE',
       'CAP - NASSAU COUNTY JAIL NY STATE',
       'NEW GENERAL AREA, NON-SPECIFIC', 'WENDE CORRECTIONAL FACILITY',
       'GREENE COUNTY', 'TIOGA COUNTY', 'FISHKILL CORRECTIONAL FACILITY',
       'WAYNE COUNTY', 'FUGITIVE OPERATIONS NY State',
       'ONEIDA COUNTY JAIL', 'LAKEVIEW CORRECTIONAL FACILITY',
       'ERIE COUNTY JAIL', 'At large arrest Nassau County',
       'GENESEE COUNTY', 'CAP - PUTNAM COUNTY JAIL NY STATE',
       'ALBANY COUNTY JAIL', 'ST. LAWRENCE COUNTY',
       'CAP - WOODBURY TOWN POLICE DEPARTMENT, NY STATE',
       'CHENANGO COUNTY', 'NON-DETAINED AND JUVENILE', 'ONEIDA COUNTY',
       'BROOME COUNTY JAIL', 'ORLEANS COUNTY',
       'CAP - COUNTY, STATE, LEA REF NY STATE',
       'HAR GENERAL AREA, NON-SPECIFIC', 'WARREN COUNTY',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'CAP - ULSTER CORRECTIONAL FACILITY NY STATE',
       'SHAWANGUNK CORRECTIONAL FACILITY',
       'WYOMING CORRECTIONAL FACILITY', 'WYOMING COUNTY JAIL',
       'ORLEANS COUNTY JAIL',
       'CAP - BEDFORD CORRECTIONAL FACILITY NY STATE',
       'WOODBOURNE CORRECTIONAL FACILITY', 'NIAGARA COUNTY',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK', 'SCHOHARIE COUNTY',
       'ULSTER CORRECTIONAL FACILITY', 'WARREN COUNTY JAIL',
       'SCHENECTADY COUNTY JAIL', 'At large arrest Suffolk County',
       'MADISON COUNTY', 'ICE ERO NEWARK', 'DELAWARE COUNTY JAIL',
       'VCAS-FACILITY ARREST NY', 'ONONDAGA COUNTY JAIL', 'CAYUGA COUNTY',
       nan, 'CAP - USM - EASTERN DISTRICT NY State', 'ONTARIO COUNTY',
       'OTISVILLE CORRECTIONAL FACILITY',
       'CAP - US FEDERAL PROBATION NY STATE',
       'WALLKILL CORRECTIONAL FACILITY',
       'CAP - DUTCHESS COUNTY JAIL  NY STATE', 'WASHINGTON COUNTY',
       'ESSEX COUNTY', 'JEFFERSON COUNTY JAIL',
       'AUBURN CORRECTIONAL FACILITY', 'MARCY CORRECTIONAL FACILITY',
       'CHM GENERAL AREA, NON-SPECIFIC', 'MONTGOMERY COUNTY',
       'CAP - OBCC - OTIS BANTUM CORRECTIONAL CENTER NY STATE',
       'LIVINGSTON COUNTY JAIL', 'BARE HILL CORRECTIONAL FACILITY',
       'OTSEGO COUNTY', 'CAP - SPRING VALLEY POLICE DEPARTMENT, NY STATE',
       'BUF GENERAL AREA, NON-SPECIFIC',
       'FIVE POINTS CORRECTIONAL FACILITY',
       'CAP - ORANGE COUNTY JAIL NY STATE', 'CAP At-large Nassau County',
       'SARATOGA COUNTY JAIL', 'JEFFERSON COUNTY',
       'UNITED STATES CITIZENSHIP AND IMMIGRATION SERVICES NYC',
       'OSWEGO COUNTY', 'STUBEN COUNTY JAIL',
       'CAP - MOUNT KISCO POLICE DEPARTMENT NY STATE',
       'CAP - RNDC - ROBERT N. DAVOREN CENTER NY STATE',
       'CAYUGA CORRECTIONAL FACILITY', 'SING SING CORRECTIONAL FACILITY',
       'BROOME COUNTY', 'WYOMING COUNTY',
       'CAP - EMTC - ERIC M. TAYLOR CENTER NY STATE',
       'RIVERVIEW CORRECTIONAL FACILITY',
       'CAP - PUTNAM COUNTY SHERRIFFS DEPARTMENT, NY STATE',
       'ALTONA CORRECTIONAL FACILITY', 'BOP BROOKLYN',
       'CAP - BOP MANHATTAN NY STATE', 'NEWARK CITY',
       'MEM GENERAL AREA, NON-SPECIFIC', 'SENECA COUNTY',
       'NIAGARA COUNTY JAIL', 'MOHAWK CORRECTIONAL FACILITY',
       'CAP - BEACON POLICE DEPARTMENT, NY STATE',
       'SYR GENERAL AREA, NON-SPECIFIC', 'FRANKLIN COUNTY',
       'MONROE COUNTY JAIL', 'DELAWARE COUNTY', 'ONTARIO COUNTY JAIL',
       'CAP - RMSC - ROSE M. SINGER CENTER NY STATE',
       'WAS GENERAL AREA, NON-SPECIFIC', 'ESSEX COUNTY HOC',
       'CAP - MIDDLETOWN CITY POLICE DEPARTMENT, NY STATE',
       'CAP - PUTNAM COUNTY PROBATION  NY STATE',
       'ORLEANS CORRECTIONAL FACILITY',
       'CAP - ROCKLAND COUNTY JAIL NY STATE',
       'BUFFALO GENERAL - Do Not Use', 'ATTICA CORRECTIONAL FACILITY',
       'COLLINS CORRECTIONAL FACILITY', 'CAP - USM - MANHATTAN NY State',
       'COLUMBIA COUNTY', 'CAP - ROCKLAND COUNTY PROBATION  NY STATE',
       'STUEBEN COUNTY', 'MADISON COUNTY JAIL',
       'CAP - MIDDLETOWN POLICE DEPARTMENT NY STATE', 'CHILDRENS VILLAGE',
       'FULTON COUNTY', 'CAP - UNITED STATES PROBATION SDNY NY STATE',
       'GROVELAND CORRECTIONAL FACILITY',
       'CAP - WESTCHESTER COUNTY POLICE DEPARTMENT, NY STATE',
       'RENSSELAER COUNTY JAIL', 'CATTARAUGUS COUNTY JAIL',
       'ALLEGANY COUNTY', 'GENESSE COUNTY JAIL',
       'GREENE CORRECTIONAL FACILITY', 'TOMPKINS COUNTY JAIL',
       'COXSACKIE CORRECTIONAL FACILITY', 'CLINTON COUNTY JAIL',
       'CAP - CHESTER VILLAGE POLICE DEPARTMENT, NY STATE',
       'ST. LAWRENCE COUNTY JAIL', 'CLINTON CORRECTIONAL FACILITY',
       'WASHINGTON CORRECTIONAL FACILITY',
       'GREEN HAVEN CORRECTIONAL FACILITY', 'LIVINGSTON COUNTY',
       'GREENE COUNTY JAIL', 'CORTLAND COUNTY', 'CLIFTON PD',
       'EPC GENERAL AREA, NON-SPECIFIC',
       'CAP - MOUNT VERNON CITY POLICE DEPARTMENT NY STATE',
       'ADIRONDACK CORRECTIONAL FACILITY',
       'CAP - NASSAU COUNTY PROBATION AND PAROLE NY STATE',
       'CAPE VINCENT CORRECTIONAL FACILITY', 'JFK INSPECTIONS',
       'XBU GENERAL AREA, NON-SPECIFIC', 'XNY GENERAL AREA, NON-SPECIFIC',
       'CHAMPLAIN POE', 'PRO FUGOPS', 'LEWISTON BRIDGE POE', 'FUG OPS CT',
       'ATD MA STATE', 'PEACE BRIDGE POE',
       'PIT GENERAL AREA, NON-SPECIFIC',
       'CAP - PORT JERVIS CITY POLICE DEPARMENT, NY STATE',
       'HARTFORD, CT', 'RAINBOW BRIDGE POE',
       'GRM GENERAL AREA, NON-SPECIFIC',
       'CAP - ORANGE COUNTY PROBATION  NY STATE',
       'MONTGOMERY COUNTY JAIL', 'NEWARK PD',
       'PHI GENERAL AREA, NON-SPECIFIC', 'ALBION CORRECTIONAL FACILITY',
       'FUG OPS - LOS ANGELES, CA STATE', 'WASHINGTON COUNTY JAIL',
       'Nassau County Jail', 'BUFFALO FEDERAL DETENTION FACILITY',
       'TIOGA COUNTY JAIL', 'ECP GENERAL AREA, NON-SPECIFIC',
       'HUDSON COUNTY JAIL', 'CORTLAND COUNTY JAIL', 'CHEMUNG COUNTY',
       'ATLANTA, GA', 'LONG BRANCH PD',
       'CAP - WHITE PLAINS CITY POLICE NY STATE',
       'CAP - FALLSBURG POLICE DEPARTMENT NY STATE', 'TOMPKINS COUNTY',
       'OCP GENERAL AREA, NON-SPECIFIC'], dtype=object)

In [36]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [40]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [41]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
193,2025-07-14 10:50:35,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,ECUADOR,Male,2025-08-12 00:00:00,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,004261c6479843c1a6c5c3fad5a36df26570d405
259,2025-06-13 17:34:11,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,3-Voluntary Departure Confirmed,...,PERU,Female,2025-07-17 00:00:00,2025-07-08 00:00:00,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,0057ba0eb90da7e66b47cc5f6a010ed7c27e102e
694,2025-07-28 09:57:24,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,TURKIYE,Male,2025-11-21 00:00:00,2025-10-21 00:00:00,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00ec58c9265babbeed11c7e981323cb55eceaf9a
1851,2025-07-28 14:27:27,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,B-Relief Granted,...,TURKIYE,Male,NaN,NaN,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,025ee8416384d932c30933a426e6b4c7c326212c
1920,2025-06-29 08:35:08,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,MEXICO,Male,2025-07-14 00:00:00,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,027534a9d64af83bb0c69d3a75c04e107fbd892b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180946,2026-01-12 10:52:18,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUINEA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fb57260c30e93cc6de984dd61ae4ae20470d82fa
181196,2025-12-18 12:27:18,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,INDIA,Male,NaN,NaN,ALBANY COUNTY,ICE Wall FY26,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fbafaac8f1e93b9f882b488265c9bfa514337919
181397,2025-12-02 08:18:41,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Male,NaN,NaN,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fbf3a0d47ab7ef7707d3b98a455ee77ad347b3e7
181401,2025-11-19 11:59:32,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,ACTIVE,...,EL SALVADOR,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,fbf6197e24defb4cc263b427ffd6b1b790c47491
183874,2025-10-17 09:20:31,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,NICARAGUA,Male,2025-11-13 00:00:00,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,ff72559666884b8a873bd40200cdaf181c05b356

In [42]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY                     340
ALBANY COUNTY                       285
RENSSELAER COUNTY                    82
WARREN COUNTY                        29
GREENE COUNTY                        13
SCHENECTADY COUNTY JAIL               8
SARATOGA COUNTY JAIL                  5
RENSSELAER COUNTY JAIL                3
WARREN COUNTY JAIL                    2
WASHINGTON CORRECTIONAL FACILITY      1
WASHINGTON COUNTY JAIL                1
Name: Apprehension Site Landmark, dtype: int64