In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/RawData/2026-ICLI-00005_Arrests_FY23_20260311_Redacted.xlsx')

In [3]:
df

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172938,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172939,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172940,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172941,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172942,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172943 entries, 0 to 172942
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   ERO LESA Statistical Tracking Unit  172941 non-null  object
 1   Unnamed: 1                          11 non-null      object
 2   Unnamed: 2                          124596 non-null  object
 3   Unnamed: 3                          1 non-null       object
 4   Unnamed: 4                          169755 non-null  object
 5   Unnamed: 5                          172938 non-null  object
 6   Unnamed: 6                          172938 non-null  object
 7   Unnamed: 7                          172938 non-null  object
 8   Unnamed: 8                          172938 non-null  object
 9   Unnamed: 9                          169398 non-null  object
 10  Unnamed: 10                         169398 non-null  object
 11  Unnamed: 11                         65237 non-null   object
 12  Unnamed: 12                         169398 non-null  object
 13  Unnamed: 13                         172938 non-null  object
 14  Unnamed: 14                         172938 non-null  object
 15  Unnamed: 15                         172938 non-null  object
 16  Unnamed: 16                         172938 non-null  object
 17  Unnamed: 17                         65321 non-null   object
 18  Unnamed: 18                         71181 non-null   object
 19  Unnamed: 19                         166638 non-null  object
 20  Unnamed: 20                         74925 non-null   object
 21  Unnamed: 21                         172938 non-null  object
 22  Unnamed: 22                         169398 non-null  object
 23  Unnamed: 23                         55529 non-null   object
 24  Unnamed: 24                         170660 non-null  object
dtypes: object(25)
memory usage: 33.0+ MB

In [5]:
df2 = df.iloc[5:]

In [6]:
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
7,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
8,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
9,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172938,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172939,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172940,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172941,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172942,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [7]:
df2.columns = df2.iloc[0]
df_titled = df2[1:].reset_index(drop=True)

In [8]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
1,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
2,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
3,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
4,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172932,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172933,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172934,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172935,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172936,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [9]:
## turn the column into datetime
df_titled['Apprehension Date'] = pd.to_datetime(df_titled['Apprehension Date'])

In [ ]:
df_titled

In [11]:
## create a subset of data for only 2025 and 2026 
df_2022 = df_titled[df_titled['Apprehension Date'] < '2023-01-01']

In [13]:
df_2022

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
4,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
6,2022-10-20 07:51:00,NaN,INDIANA,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,"INP GENERAL AREA, NON-SPECIFIC",-,"ERO - Indianapolis, IN Sub-Office",3 Other Immigration Violator,NaN,0001881592ace06cdaa5af0f8bf065385a6e3491
7,2022-12-14 08:50:00,NaN,NaN,NaN,Denver Area of Responsibility,Mobile Criminal Alien Team,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,DENVER COUNTY,NaN,"DENVER, CO, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00019fa9e0aa94625220c91d01d1285f5accf081
9,2022-11-03 11:21:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00037689c6eb841eef84ffa417b8669c914acf78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171367,2022-12-30 10:24:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,NaN
171369,2022-12-30 12:14:54,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,NaN,NaN,"COLUMBUS, NM, POE",NaN,NaN,NaN
171370,2022-12-31 08:29:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
171371,2022-12-31 09:04:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2022-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,NaN
171830,2022-12-14 11:00:00,NaN,NaN,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,Located,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"CHI GENERAL AREA, NON-SPECIFIC",NaN,"CHICAGO, IL, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [14]:
df_2022.to_csv('RawData/2022_pt1.csv', index=False)