In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/RawData/2026-ICLI-00005_Arrests_FY24_20260311_Redacted.xlsx')

In [3]:
df

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113839,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113840,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113841,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113842,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113843,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113844 entries, 0 to 113843
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   ERO LESA Statistical Tracking Unit  113842 non-null  object
 1   Unnamed: 1                          17 non-null      object
 2   Unnamed: 2                          82880 non-null   object
 3   Unnamed: 3                          1 non-null       object
 4   Unnamed: 4                          111739 non-null  object
 5   Unnamed: 5                          113839 non-null  object
 6   Unnamed: 6                          113839 non-null  object
 7   Unnamed: 7                          113839 non-null  object
 8   Unnamed: 8                          113839 non-null  object
 9   Unnamed: 9                          110875 non-null  object
 10  Unnamed: 10                         110875 non-null  object
 11  Unnamed: 11                         70792 non-null   object
 12  Unnamed: 12                         110875 non-null  object
 13  Unnamed: 13                         113839 non-null  object
 14  Unnamed: 14                         113839 non-null  object
 15  Unnamed: 15                         113839 non-null  object
 16  Unnamed: 16                         113839 non-null  object
 17  Unnamed: 17                         70824 non-null   object
 18  Unnamed: 18                         73079 non-null   object
 19  Unnamed: 19                         108335 non-null  object
 20  Unnamed: 20                         31693 non-null   object
 21  Unnamed: 21                         113839 non-null  object
 22  Unnamed: 22                         110875 non-null  object
 23  Unnamed: 23                         58992 non-null   object
 24  Unnamed: 24                         112373 non-null  object
dtypes: object(25)
memory usage: 21.7+ MB

In [5]:
df2 = df.iloc[5:]

In [6]:
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
7,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
8,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
9,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113839,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113840,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113841,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113842,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113843,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [7]:
df2.columns = df2.iloc[0]
df_titled = df2[1:].reset_index(drop=True)

In [8]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
2,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
3,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
4,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113833,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113834,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113835,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113836,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113837,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [9]:
## turn the column into datetime
df_titled['Apprehension Date'] = pd.to_datetime(df_titled['Apprehension Date'])

In [10]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2024-06-13 08:06:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Deported/Removed,...,HONDURAS,Male,2024-06-26 00:00:00,2023-12-07 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,1,000058df2daf065f42816437ebf455e2d0d38558
2,2024-02-02 09:54:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,Non-Detained Docket Control,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-07-05 00:00:00,2025-05-23 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,0000aec67e823c9306515cc63f285a76fc3b6591
3,2024-03-14 09:49:00,NaN,WASHINGTON,NaN,Seattle Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-03-26 00:00:00,2023-06-30 00:00:00,FEDERAL DETENTION CENTER (FDC),Criminal Alien Program Surge Enforcement Team ...,"SEATTLE, WA, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,0000c5cf8abc2d9f6b8aa424933343957c7801bb
4,2024-08-06 12:17:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000c68c7cf317c4fd47056ac433e9a0d994a1e4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113833,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113834,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113835,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113836,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113837,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [15]:
## create a subset of data for only 2025 and 2026 
df_2023 = df_titled[df_titled['Apprehension Date'] < '2024-01-01']

In [16]:
df_2022

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
8,2023-11-03 11:37:00,NaN,NaN,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-12-20 00:00:00,2016-04-09 00:00:00,STUART,NaN,"ERO - Stuart, FL Sub Office",1 Convicted Criminal,3,00038f76045b3d1bb8b62d85365e29a9924a58f1
9,2023-11-01 07:54:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-11-01 00:00:00,2017-07-02 00:00:00,VENTURA FUGITIVE OPERATIONS,-,"ERO - Ventura, CA Sub Office",1 Convicted Criminal,2,0003a23f3f22d9a40e269cf7401c551a29a88c24
16,2023-11-24 11:12:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,COLOMBIA,Male,NaN,2024-06-20 00:00:00,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0006989f31392d9aa50a51d46c451395b0547050
19,2023-11-01 11:42:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,2024-10-10 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,000732077b82caf319021e0154c64f9a77a6118e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112744,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
112745,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,NaN
112746,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
112747,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
112748,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [17]:
df_2023.to_csv('RawData/2023.csv', index=False)