In [32]:
## import necessary libraries
import pandas as pd

In [33]:
df = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/RawData/2026-ICLI-00005_Arrests_FY26_20260311_Redacted.xlsx')

In [34]:
df

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2026YTD (10/01/20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191547,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191548,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191549,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191550,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191551,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191552 entries, 0 to 191551
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   ERO LESA Statistical Tracking Unit  191550 non-null  object
 1   Unnamed: 1                          189072 non-null  object
 2   Unnamed: 2                          189106 non-null  object
 3   Unnamed: 3                          1 non-null       object
 4   Unnamed: 4                          191150 non-null  object
 5   Unnamed: 5                          191547 non-null  object
 6   Unnamed: 6                          191547 non-null  object
 7   Unnamed: 7                          191547 non-null  object
 8   Unnamed: 8                          191547 non-null  object
 9   Unnamed: 9                          184177 non-null  object
 10  Unnamed: 10                         184177 non-null  object
 11  Unnamed: 11                         115068 non-null  object
 12  Unnamed: 12                         184177 non-null  object
 13  Unnamed: 13                         191546 non-null  object
 14  Unnamed: 14                         191546 non-null  object
 15  Unnamed: 15                         191547 non-null  object
 16  Unnamed: 16                         191547 non-null  object
 17  Unnamed: 17                         115088 non-null  object
 18  Unnamed: 18                         84114 non-null   object
 19  Unnamed: 19                         189996 non-null  object
 20  Unnamed: 20                         31937 non-null   object
 21  Unnamed: 21                         191547 non-null  object
 22  Unnamed: 22                         184177 non-null  object
 23  Unnamed: 23                         52240 non-null   object
 24  Unnamed: 24                         184306 non-null  object
dtypes: object(25)
memory usage: 36.5+ MB

In [36]:
df2 = df.iloc[5:]

In [37]:
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
7,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
8,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
9,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191547,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191548,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191549,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191550,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191551,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [38]:
df2.columns = df2.iloc[0]
df_titled = df2[1:].reset_index(drop=True)

In [39]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
3,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
4,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,000236c508a3b3fd90b47464c6790ebd2ced3228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191541,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191542,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191543,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191544,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191545,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [40]:
## turn the column into datetime
df_titled['Apprehension Date'] = pd.to_datetime(df_titled['Apprehension Date'])

In [41]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
3,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
4,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,000236c508a3b3fd90b47464c6790ebd2ced3228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191541,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191542,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191543,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
191544,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
191545,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [42]:
## create a subset of data for only 2025 and 2026 
df_2025 = df_titled[df_titled['Apprehension Date'] < '2026-01-01']

In [43]:
df_2025

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-11-16 14:21:59,Targeted,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-11-28 00:00:00,2024-08-01 00:00:00,FRU - ALL AREAS INISDE BEXAR COUNTY,-,"ERO - Austin, TX Sub Office",3 Other Immigration Violator,NaN,0000004d7b875782a3b6f2b460f98c0750a5a899
1,2025-11-05 14:29:30,Collateral,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Female,2025-12-02 00:00:00,2025-10-28 00:00:00,"DLR GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Del Rio, TX Sub Office",1 Convicted Criminal,3,0000d8cb192bc69cea76779ab037c4a6d98f176e
2,2025-12-14 08:18:33,Targeted,UTAH,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-20 00:00:00,2025-12-15 00:00:00,"SLC GENERAL AREA, NON-SPECIFIC",-,"SALT LAKE CITY, UT, DOCKET CONTROL OFFICE",1 Convicted Criminal,2,000123c8701799c3f1c69fc5b9237441afcf6161
4,2025-11-19 07:44:46,Targeted,ILLINOIS,NaN,Chicago Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2026-01-28 00:00:00,2026-01-22 00:00:00,CHIFUGITIVE OPERATIONS,-,"CHICAGO, IL, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,000236c508a3b3fd90b47464c6790ebd2ced3228
5,2025-10-09 14:24:47,Targeted,TEXAS,NaN,El Paso Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,2025-07-12 00:00:00,"EPC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - El Paso, TX SPC Sub-Office",1 Convicted Criminal,3,0002a26f2085a370bf4be4fec089a1124f2f4e03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189392,2025-12-31 16:42:51,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",-,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
189393,2025-12-31 22:42:46,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",---,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
189394,2025-12-31 20:00:25,Targeted,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,NaN
189517,2025-12-15 12:54:00,Collateral,CALIFORNIA,NaN,NaN,Law Enforcement Area Response Units,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"LNBGENERAL AREA, NON-SPECIFIC",NaN,HSI SAC LOS ANGELES,NaN,NaN,NaN
190456,2025-12-11 03:55:00,Targeted,TEXAS,NaN,Dallas Area of Responsibility,287g Task Force,ICE,287(g) Program,2 Pending Criminal Charges,NaN,...,MEXICO,Male,NaN,NaN,PANOLA COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN

In [44]:
df_2025.to_csv('RawData/2025pt2.csv', index=False)