In [1]:
## import necessary libraries
import pandas as pd

In [13]:
df = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/RawData/2026-ICLI-00005_Arrests_FY25_20260311_Redacted.xlsx')

In [14]:
df

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235144,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235145,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235146,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235147,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235148,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235149 entries, 0 to 235148
Data columns (total 25 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   ERO LESA Statistical Tracking Unit  235147 non-null  object
 1   Unnamed: 1                          56923 non-null   object
 2   Unnamed: 2                          209510 non-null  object
 3   Unnamed: 3                          1 non-null       object
 4   Unnamed: 4                          233441 non-null  object
 5   Unnamed: 5                          235144 non-null  object
 6   Unnamed: 6                          235144 non-null  object
 7   Unnamed: 7                          235144 non-null  object
 8   Unnamed: 8                          235144 non-null  object
 9   Unnamed: 9                          230258 non-null  object
 10  Unnamed: 10                         230258 non-null  object
 11  Unnamed: 11                         188535 non-null  object
 12  Unnamed: 12                         230258 non-null  object
 13  Unnamed: 13                         235143 non-null  object
 14  Unnamed: 14                         235143 non-null  object
 15  Unnamed: 15                         235144 non-null  object
 16  Unnamed: 16                         235144 non-null  object
 17  Unnamed: 17                         188571 non-null  object
 18  Unnamed: 18                         160402 non-null  object
 19  Unnamed: 19                         233251 non-null  object
 20  Unnamed: 20                         39808 non-null   object
 21  Unnamed: 21                         235144 non-null  object
 22  Unnamed: 22                         230258 non-null  object
 23  Unnamed: 23                         94719 non-null   object
 24  Unnamed: 24                         231786 non-null  object
dtypes: object(25)
memory usage: 44.9+ MB

In [16]:
df2 = df.iloc[5:]

In [17]:
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
7,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
8,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
9,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235144,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235145,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235146,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235147,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235148,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [18]:
df2.columns = df2.iloc[0]
df_titled = df2[1:].reset_index(drop=True)

In [19]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
1,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
4,2025-02-19 00:00:00,NaN,KANSAS,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-04-04 00:00:00,2020-02-07 00:00:00,"WIC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Wichita, KS Sub-Office",2 Pending Criminal Charges,NaN,00019569acea0c5120fc0e55d6254c7d4aad2b22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235138,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235139,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235140,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235141,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235142,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [20]:
## turn the column into datetime
df_titled['Apprehension Date'] = pd.to_datetime(df_titled['Apprehension Date'])

In [ ]:
df_titled

In [21]:
## create a subset of data for only 2025 and 2026 
df_2025 = df_titled[df_titled['Apprehension Date'] > '2025-01-20']

In [22]:
df_2025

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2025-09-17 11:34:21,Targeted,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,6-Deported/Removed - Deportability,...,COLOMBIA,Male,2025-11-13 00:00:00,2022-05-18 00:00:00,DALLAS COUNTY GENERAL AREA,DHS & DOJ 6 MONTH - NATIONWIDE OP TO INCREASE ...,"DALLAS, TX, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0000215186a4071ae5bc250f63e6baa60b286c30
1,2025-07-15 12:35:19,NaN,INDIANA,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-07-25 00:00:00,2025-07-15 00:00:00,"MARION COUNTY SHERIFF'S OFFICE, INDIANAPOLIS, ...",NaN,"ERO - Indianapolis, IN Sub-Office",2 Pending Criminal Charges,NaN,0000518998357378d65efc37aee9a476ad110db1
2,2025-09-19 15:18:01,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Deported/Removed,...,GUATEMALA,Male,2025-09-24 00:00:00,2019-02-10 00:00:00,"PHI GENERAL AREA, NON-SPECIFIC",NaN,"PHILADELPHIA, PA, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,000071be2f67e88489f0c0f0c281ff6f9cda4dda
3,2025-01-26 14:49:00,NaN,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,GUATEMALA,Male,2025-05-27 00:00:00,NaN,"MECKLENBURG COUNTY, NC",-,"ERO - Charlotte, NC Sub-Office",3 Other Immigration Violator,NaN,0000b5b7a22827fe95d32ba770cc8ae9cc669fa9
4,2025-02-19 00:00:00,NaN,KANSAS,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Male,2025-04-04 00:00:00,2020-02-07 00:00:00,"WIC GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Wichita, KS Sub-Office",2 Pending Criminal Charges,NaN,00019569acea0c5120fc0e55d6254c7d4aad2b22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235138,2025-09-30 16:58:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2025-09-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",ICE ERO HQ authorized operation,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
235139,2025-09-30 19:52:05,Targeted,TEXAS,NaN,Houston Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"MTG GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Montgomery County, TX Sub Office",NaN,NaN,NaN
235140,2025-09-30 20:09:40,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235141,2025-09-30 20:32:00,Targeted,CALIFORNIA,NaN,San Diego Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,"San Diego, CA",NaN,"SAN DIEGO, CA, DOCKET CONTROL OFFICE",NaN,NaN,NaN
235142,2025-08-19 12:38:00,Targeted,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",NaN,NaN,NaN

In [24]:
df_2025.to_csv('RawData/2025_pt1.csv', index=False)